apiVersion: v1
kind: Service
metadata:
  name: content-engine # <srv-name>.<srv-namesapce>.svc.cluster.local
spec:
  selector:
    app: web
  # type: LoadBalancer # -> Node Balancer
  # type: NodePort # public ip -> attached to the vm
  type: ClusterIP # private service
  ports:
    - name: http
      protocol: TCP
      port: 80 # mydomain.com -> mydomain.com:80
      targetPort: 8080